version: '3.7'

services:
  rcs-back-gql:
    build: .
    image: rcs-gql-servidor:poc
    container_name: rcs-gql-backend
    ports:
      - "8008:8008"
    restart: always
    volumes:
      - "./src:/app/src"
      - "./data:/app/data"
    networks:
      - poc-rcs

networks:
  poc-rcs:
    name: poc-rcs
    external: true